#pragma once

#define CONFIG_UL_RGB_SMOOTH_HZ 200
#define CONFIG_UL_GAMMA_ENABLE 0

#define CONFIG_UL_RGB0_ENABLED 1
#define CONFIG_UL_RGB0_PWM_HZ 1000
#define CONFIG_UL_RGB0_LEDC_MODE 0
#define CONFIG_UL_RGB0_R_GPIO 1
#define CONFIG_UL_RGB0_R_LEDC_CH 0
#define CONFIG_UL_RGB0_G_GPIO 2
#define CONFIG_UL_RGB0_G_LEDC_CH 1
#define CONFIG_UL_RGB0_B_GPIO 3
#define CONFIG_UL_RGB0_B_LEDC_CH 2

#define CONFIG_UL_RGB1_ENABLED 0
#define CONFIG_UL_RGB1_PWM_HZ 1000
#define CONFIG_UL_RGB1_LEDC_MODE 0
#define CONFIG_UL_RGB1_R_GPIO 4
#define CONFIG_UL_RGB1_R_LEDC_CH 3
#define CONFIG_UL_RGB1_G_GPIO 5
#define CONFIG_UL_RGB1_G_LEDC_CH 4
#define CONFIG_UL_RGB1_B_GPIO 6
#define CONFIG_UL_RGB1_B_LEDC_CH 5

#define CONFIG_UL_RGB2_ENABLED 0
#define CONFIG_UL_RGB2_PWM_HZ 1000
#define CONFIG_UL_RGB2_LEDC_MODE 0
#define CONFIG_UL_RGB2_R_GPIO 7
#define CONFIG_UL_RGB2_R_LEDC_CH 6
#define CONFIG_UL_RGB2_G_GPIO 8
#define CONFIG_UL_RGB2_G_LEDC_CH 7
#define CONFIG_UL_RGB2_B_GPIO 9
#define CONFIG_UL_RGB2_B_LEDC_CH 8

#define CONFIG_UL_RGB3_ENABLED 0
#define CONFIG_UL_RGB3_PWM_HZ 1000
#define CONFIG_UL_RGB3_LEDC_MODE 0
#define CONFIG_UL_RGB3_R_GPIO 10
#define CONFIG_UL_RGB3_R_LEDC_CH 9
#define CONFIG_UL_RGB3_G_GPIO 11
#define CONFIG_UL_RGB3_G_LEDC_CH 10
#define CONFIG_UL_RGB3_B_GPIO 12
#define CONFIG_UL_RGB3_B_LEDC_CH 11
