#pragma once

#define CONFIG_UL_WS0_ENABLED 1
#define CONFIG_UL_WS1_ENABLED 1
#define CONFIG_UL_WS0_GPIO 1
#define CONFIG_UL_WS1_GPIO 2
#define CONFIG_UL_WS0_PIXELS 5
#define CONFIG_UL_WS1_PIXELS 6
#define CONFIG_UL_WS2812_FPS 60
#define CONFIG_UL_GAMMA_ENABLE 0
#define CONFIG_UL_IS_ESP32C3 0
#define CONFIG_UL_HAS_PSRAM 0

#define MALLOC_CAP_8BIT 0
