#pragma once

#define CONFIG_UL_WHITE_SMOOTH_HZ 200

#define CONFIG_UL_WHT0_ENABLED 1
#define CONFIG_UL_WHT0_GPIO 1
#define CONFIG_UL_WHT0_LEDC_CH 0
#define CONFIG_UL_WHT0_PWM_HZ 1000

#define CONFIG_UL_WHT1_ENABLED 0
#define CONFIG_UL_WHT1_GPIO 2
#define CONFIG_UL_WHT1_LEDC_CH 1
#define CONFIG_UL_WHT1_PWM_HZ 1000

#define CONFIG_UL_WHT2_ENABLED 0
#define CONFIG_UL_WHT2_GPIO 3
#define CONFIG_UL_WHT2_LEDC_CH 2
#define CONFIG_UL_WHT2_PWM_HZ 1000

#define CONFIG_UL_WHT3_ENABLED 0
#define CONFIG_UL_WHT3_GPIO 4
#define CONFIG_UL_WHT3_LEDC_CH 3
#define CONFIG_UL_WHT3_PWM_HZ 1000

#define CONFIG_UL_IS_ESP32C3 0
